# Generated by Django 3.1.3 on 2022-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220328_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/onlinecourse_app_er.png', upload_to='course_images/'),
        ),
    ]
